---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: quay.io/redhatgov/rust-hello-world:0.1.3
        ports:
        - containerPort: 8000
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        ### Probe to allow container time to start before liveness probe takes over
        startupProbe:
          httpGet:
            port: 8000
            path: /hello/health-startup
          periodSeconds: 1
          failureThreshold: 5
        ### Probe to restart a failed container
        livenessProbe:
          httpGet:
            port: 8000
            path: /hello/health-liveness
          periodSeconds: 2
          failureThreshold: 3
        ### Probe to know when to send traffic to the container.
        readinessProbe:
          httpGet:
            port: 8000
            path: /hello/health-readiness
          periodSeconds: 1
          failureThreshold: 1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
